# Generated by Django 2.0.13 on 2019-07-09 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-id'], 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AddField(
            model_name='comment',
            name='emotion_propotion',
            field=models.BigIntegerField(default=0, verbose_name='Emotion Propotion'),
        ),
        migrations.AddField(
            model_name='post',
            name='emotion_propotion',
            field=models.BigIntegerField(default=0, verbose_name='Emotion Propotion'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='comment',
            table='blog_comment',
        ),
    ]
